FROM node:23-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN pnpm -g add turbo@^2.5.4

ARG APP_NAME

FROM base AS builder
WORKDIR /app
COPY . .
RUN turbo prune $APP_NAME --docker

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/out/json/ .
RUN pnpm install --frozen-lockfile
COPY --from=builder /app/out/full/ .

ARG GENERATE_DB
RUN [ "$GENERATE_DB" = "true" ] && pnpm turbo run db:generate || true

CMD ["turbo", "run", "dev"]